name: dotnet package

on: [push]

jobs:
  build-and-test:
    env:
      BUILD_CONFIGURATION: Release
      SOLUTION_NAME: TestProject1.sln
      ALLURE_RESULTS: TestProject1/bin/Release/net6.0/allure-results
      GH_PAGES_URL: https://github.com/rodrigognr71/todoly_tests/aquality-selenium-dotnet-template
    name: Run tests and generate Allure Report

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install Google Chrome
        run: |
          chmod +x ./scripts/InstallChrome.sh
          ./scripts/InstallChrome.sh   
      - name: Set up Selenium ChromeDriver
        run: |
          sudo apt-get install -y chromium-chromedriver
      - name: Print contents of /usr/bin
        run: ls -al /usr/bin
      - name: Check port accessibility
        run: nc -vz localhost 43169
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet test --no-restore --verbosity normal
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: "Publish test results"
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './TestProject1/bin/Debug/net6.0/allure-results'
          keep_files: true
          user_name: rodrigognr71
          user_email: rodrigognr71@gmail.com
          publish_branch: gh_page  
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: './TestProject1/bin/Debug/net6.0/allure-results'
          gh_pages: gh-pages
          allure_report: allure-report
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-report    
